version: 2
updates:
  - package-ecosystem: "maven"
    directory: "/java/SqsBatchProcessing/Functions"
    schedule:
      interval: "daily"
    labels:
      - "maven"
      - "dependencies"
  - package-ecosystem: "maven"
      directory: "/java/CoreUtilities/Functions"
      schedule:
        interval: "daily"
      labels:
        - "maven"
        - "dependencies"